### PR TITLE
added the signup page

### PR DESCRIPTION
**Pull request by davrana**
I have created the signup page as per your mentioned requirement 
I hope u like it!
Plz accept my PR for hacktoberfest2022!

### CODE REVIEW

**Comment by MadhushaPrasad** [comment]
can you please drop a screenshot of sign up page

**Comment by davrana** [comment]
yeah sure

Screenshot

**Comment by davrana** [comment]
I hope u like it!

**Comment by MadhushaPrasad** [comment]
> I hope u like it!

actually, we have a design for this project. It will be in the readme file. we need that signup.so I can't accept this

**Review by MadhushaPrasad — APPROVED** [review]

**Pull request merged**
