### PR TITLE
Implemented Responsive Contact Us Component

### PR DESCRIPTION
**Pull request by Janani-Balasooriya**
I have implemented the Contact Us component with a responsive design that matches the Figma file's UI, using the same sizes specified in the Figma design.

Fixes: Closes issue #26 

Screenshots:

I am open to feedback and suggestions for further improvements. Thank you for considering my pull request.

Thank you!
Janani

### CODE REVIEW

**Comment by Janani-Balasooriya** [comment]
Hi @MadhushaPrasad, My pull request is ready for merging. It has the solution for issue #26. Could you please review it when you have a moment?
Thank you!

**Review by supuna97 — APPROVED** [review]

**Comment by supuna97** [comment]
Hi @Janani-Balasooriya, If you can also add validations, that's a great job.

**Comment by Janani-Balasooriya** [comment]
Thank you for your feedback, @supuna97!! I will add validations too.

**Comment by Janani-Balasooriya** [comment]
I've added validation to the Contact Us component. Please review the changes when you have a moment.

Screenshot:
image


Thank you!

**Review by MadhushaPrasad — APPROVED** [review]
great job

**Pull request merged**
